export const QUOTES: { theme: string; message: string }[] = [
  { theme: "discipline", message: "The physician you are becoming is built in quiet hours no one else will see." },
  { theme: "consistency", message: "MCCQE1 is not a sprint of brilliance. It is a practice of returning to the desk." },
  { theme: "medicine", message: "Every block you finish is another clinical pattern you will recognize for a patient one day." },
  { theme: "canadian-journey", message: "MBBS was the foundation. This season is the bridge to practising medicine in Canada." },
  { theme: "confidence", message: "You have already done the hardest part: beginning again in a new medical culture." },
  { theme: "family", message: "The people who believe in you do not need a perfect day. They need you to keep going." },
  { theme: "difficult-day", message: "A heavy study day still counts. So does a short one. Presence is the standard, not theatre." },
  { theme: "resilience", message: "You have sat exams before. This one asks for Canadian framing, not a smaller doctor." },
  { theme: "weak-subjects", message: "The subject that feels least natural is often the one that will raise your floor the most." },
  { theme: "exam-prep", message: "Readiness is not a feeling. It is coverage, accuracy, and calm under timed conditions." },
  { theme: "milestones", message: "You do not need a booked date to take this seriously. The work itself is the commitment." },
  { theme: "discipline", message: "Start the session. One honest block. End it when you are done. That is how a Canadian practice is earned." },
  { theme: "consistency", message: "Streaks are not trophies. They are proof that Nida showed up for Nida." },
  { theme: "medicine", message: "Ethics, public health, and communication are not extras here. They are the Canadian exam’s grammar." },
  { theme: "canadian-journey", message: "You are not leaving your MBBS behind. You are translating it into a system that will trust you with lives." },
  { theme: "confidence", message: "Doubt is information, not a verdict. Answer it with another carefully reviewed block." },
  { theme: "family", message: "Let the household hold the rest of the day. Your hour at this desk is already a gift to the future." },
  { theme: "difficult-day", message: "If the material will not settle, log what you did and rest. Fatigue is not failure." },
  { theme: "resilience", message: "International graduates who pass this exam did not feel ready every morning. They were methodical." },
  { theme: "weak-subjects", message: "Psychiatry, ethics, and preventive care often decide the margin. Treat them with the same respect as cardiology." },
  { theme: "exam-prep", message: "A question you miss today is cheaper than the same miss on exam day. Collect the lesson." },
  { theme: "milestones", message: "First session, first hundred questions, first mock: none of them arrive by accident." },
  { theme: "discipline", message: "Protect the start time. The mind follows the calendar more faithfully than motivation." },
  { theme: "consistency", message: "Four focused hours beat eight distracted ones. Quality is a form of kindness to your future self." },
  { theme: "medicine", message: "Think like the physician in the stem: what would you do next for this patient in a Canadian clinic?" },
  { theme: "canadian-journey", message: "Guidelines, consent, and resource stewardship are not trivia. They are how care is practised here." },
  { theme: "confidence", message: "You are allowed to be both a learner and already a doctor. Those identities can sit at the same table." },
  { theme: "family", message: "Someone in this house is proud of the woman who still opens the Qbank after a long day." },
  { theme: "difficult-day", message: "When accuracy dips, you have not gone backwards. You have found the next teaching point." },
  { theme: "resilience", message: "Licensure is a long corridor. Today you only have to walk the next few metres well." },
  { theme: "weak-subjects", message: "If a system feels foggy, give it a named hour this week. Avoidance is the only real delay." },
  { theme: "exam-prep", message: "Timed blocks train more than knowledge. They train the pace you will need when the clock is real." },
  { theme: "milestones", message: "Booking the exam is a decision you will earn with evidence, not with hope alone." },
  { theme: "discipline", message: "Close the extra tabs. One source, one subject, one hour. That is elite preparation, not restriction." },
  { theme: "consistency", message: "The dashboard will get smarter because you keep feeding it honest work, not because it guesses." },
  { theme: "medicine", message: "Stroke, sepsis, chest pain, first-trimester bleeding: pattern recognition is a craft. Practise it." },
  { theme: "canadian-journey", message: "MCCQE1 is a conversation with the profession you are joining. Answer in its clinical language." },
  { theme: "confidence", message: "You do not need to sound like every Canadian graduate. You need to reason like a safe one." },
  { theme: "family", message: "Love looks like a quiet house while you study, and like you coming back from the desk still yourself." },
  { theme: "difficult-day", message: "Grief for the life you paused is allowed. So is continuing. Both can be true in the same afternoon." },
  { theme: "resilience", message: "You rebuilt a medical career across countries. A question block cannot outrank that fact." },
  { theme: "weak-subjects", message: "Obstetrics and paediatrics reward repetition. Return tomorrow with less pride and more curiosity." },
  { theme: "exam-prep", message: "Review the incorrects while the reasoning is still warm. That is where the score actually moves." },
  { theme: "milestones", message: "Today’s save is a line in a record you will one day read as the winter you became ready." },
  { theme: "discipline", message: "Do not negotiate with the timer. Start it. The resistance usually leaves in the first twelve minutes." },
  { theme: "consistency", message: "Weekly hours are a conversation with your future licence. Keep the conversation civil and regular." },
  { theme: "medicine", message: "Biostatistics is how you protect patients from charming but wrong claims. Give it a real seat." },
  { theme: "canadian-journey", message: "You are preparing to be trusted in emergency departments, clinics, and wards that do not know your MBBS years yet. Show them your judgement." },
  { theme: "confidence", message: "Competence is quiet. It looks like finishing the block and writing one precise note." },
  { theme: "family", message: "This journey is shared, even when the questions are yours alone. Let that be fuel, not pressure." },
  { theme: "difficult-day", message: "If you can only do review today, do review. Maintenance is still movement." },
  { theme: "resilience", message: "There will be weeks that look flat on a chart. Flat is not failure. Flat is staying in the work." },
  { theme: "weak-subjects", message: "Public health questions feel dry until you remember they are how a country thinks about harm." },
  { theme: "exam-prep", message: "A mock is a mirror. Do not delay it until you feel photogenic. Sit it when the plan says so." },
  { theme: "milestones", message: "One hundred questions is not a personality. It is a beginning with a number attached. Keep going." },
  { theme: "discipline", message: "Protect sleep as if it were a high-yield subject. It is." },
  { theme: "consistency", message: "The most Canadian thing you can do this month is be reliable: same desk, honest logs, no theatre." },
  { theme: "medicine", message: "Geriatrics and polypharmacy are not side rooms. They are the medicine of the patients you will actually meet." },
  { theme: "canadian-journey", message: "From Karachi lecture halls to a Toronto morning: the through-line is still your duty to the next patient." },
  { theme: "confidence", message: "You are not impersonating a doctor. You are refining how this system will hear you." },
  { theme: "family", message: "When you are tired, remember who you are doing this for — including the woman who wanted a Canadian practice." },
  { theme: "difficult-day", message: "Low energy is a vital sign. Treat it. Then do the smallest complete session you can respect." },
  { theme: "resilience", message: "Paperwork, visas, and exams are different skills. You are allowed to be better at medicine than at bureaucracy." },
  { theme: "weak-subjects", message: "ENT and ophthalmology are short, high-yield, and easy to postpone. That is exactly why they belong on today’s list." },
  { theme: "exam-prep", message: "Skipped questions are data. They tell you where time, knowledge, or nerve ran out." },
  { theme: "milestones", message: "You will know you are closer when weak areas shrink and mocks stop surprising you. Not before." },
  { theme: "discipline", message: "Save the session even if it was imperfect. The record is part of the medicine: honest, dated, useful." },
  { theme: "consistency", message: "Five ordinary weekdays will outperform one heroic Sunday. Build the ordinary." },
  { theme: "medicine", message: "Rheumatology and nephrology reward mechanism over memorization. Slow down and ask why the lab moved." },
  { theme: "canadian-journey", message: "You are joining a profession that will ask you to document, to consent, and to share decisions. Practise that voice now." },
  { theme: "confidence", message: "Accuracy after volume is the only accuracy that matters. Keep the denominator honest." },
  { theme: "family", message: "A partner who builds you a study OS is not the exam. You still have to walk through it. But you are not walking alone." },
  { theme: "difficult-day", message: "If comparison appears, close it. Other people’s timelines are not a curriculum." },
  { theme: "resilience", message: "You have already survived the uncertainty of starting over. Today is smaller than that." },
  { theme: "weak-subjects", message: "Communication stations live inside MCCQE1 too. How you explain risk is part of being safe." },
  { theme: "exam-prep", message: "Do not hunt for a secret resource. Depth in the ones you chose will beat a new login." },
  { theme: "milestones", message: "When you book, it should feel like the data agreed with you, not like a dare." },
  { theme: "discipline", message: "End on time. A clean finish teaches the nervous system that this work has edges." },
  { theme: "consistency", message: "The OS remembers. Show it a real week, and it will start telling you the truth about readiness." },
  { theme: "medicine", message: "Oncology is not only protocols. It is goals of care, toxicity, and what the patient still wants." },
  { theme: "canadian-journey", message: "Canada does not need a copy of a Canadian student. It needs a physician who can think here." },
  { theme: "confidence", message: "Speak to yourself the way you would to a colleague on a night shift: direct, kind, specific." },
  { theme: "family", message: "There will be dinners you miss and mornings you protect. Both are part of becoming Dr. Nida in this country." },
  { theme: "difficult-day", message: "You can be frustrated with a score and still be on the path. Hold both without drama." },
  { theme: "resilience", message: "Licensure committees will never see this Tuesday. Your patients one day will feel its effect. That is enough." },
  { theme: "weak-subjects", message: "Urology and orthopaedics are finite. Finite things can be finished. Start the list." },
  { theme: "exam-prep", message: "Near the exam, protect judgement: sleep, mocks, incorrects. New rabbit holes are a luxury you can refuse." },
  { theme: "milestones", message: "Ready to book is a clinical impression. Gather enough evidence before you write it." },
  { theme: "canadian-journey", message: "From MBBS to MCCQE1 to a Canadian physician: today is a single, sufficient step on that line." },
  { theme: "milestones", message: "The record begins empty on purpose. The first honest session is how this operating system starts telling the truth." },
]
